### ISSUE TITLE
Trapped focus causes accessibility issues

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-geocoder#162] opened 2018-08-14 00:12 UTC
Looks like this line:

```
// TAB, ESC, LEFT, RIGHT, ENTER, UP, DOWN
if (e.metaKey || [9, 27, 37, 39, 13, 38, 40].indexOf(e.keyCode) !== -1) return;
```
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/lib/index.js#L133

... traps focus on the GeoCoder input element and doesn't allow the user to tab through the following elements cause accessibility issues.

**Comment by timchambers** [comment] 2018-08-17 19:39
This seems to be the source of a problem I'm experiencing, too. If I have a map and geocoded inside a form and I hit return in one of the other form fields, the focus is stolen back to the geocoded and the submit event doesn't get fired. Any way to disable this focus stealing?

**Comment by andrewharvey** [comment] 2018-08-17 22:59
Does anyone have an minimally reproducing example?

**Comment by 3zzy** [comment] 2018-08-19 23:35
@andrewharvey Here: https://jsfiddle.net/iaezzy/zevaw734/8/

If you try navigating via keyboard using Tab key, once you reach the geocoder element you can't focus the next button or the previous (using Shift + Tab) because the focus is trapped.

**Comment by jdaudier** [comment] 2018-08-27 22:47
I have the same bug. Does anyone have a workaround for this while we are waiting for a fix?

**Comment by 3zzy** [comment] 2018-08-27 23:26
@jdaudier Here's what I'm doing temporarily:

```
$(".mapboxgl-ctrl-geocoder input[type='text']").on('focus keydown', function (e) {  
    if (e.shiftKey && e.keyCode == 9) {
        // focus prev
    }
    else if (e.keyCode == 9) {
        focus next
    }
});
```

**Comment by jdaudier** [comment] 2018-08-31 18:36
@3zzy Thanks! It works for me but I didn't need to add the event on focus. Just curious about your reason for that.

**Comment by scottsfarley93** [comment] 2019-03-15 18:35
It looks like we could tackle this by changing the `suggestions` library with a relatively minor PR that prevents trapping `tab` events.

Specifically, changing https://github.com/tristen/suggestions/blob/gh-pages/src/suggestions.js#L59 and https://github.com/tristen/suggestions/blob/gh-pages/src/suggestions.js#L67 so that `keyCode==9` checks are no longer cases in the switch statements.

I'm not sure if this will cause any other unintended consequences though. I'll have to dig in a little more.

**Comment by scottsfarley93** [comment] 2019-03-21 16:17
This was done in #220 and will be fixed in version 4.

**Closed by scottsfarley93** 2019-03-21 16:17 UTC
Labels: bug, help wanted
