### ISSUE TITLE
Can't get a marker after searching some places

### ISSUE THREAD

**Issue by nooblzh** [mapbox/mapbox-gl-geocoder#365] opened 2020-06-16 02:37 UTC
I have a task to use vue.js to create a map application, but when I learn the example on the website, I found that i can't create a marker in geocoder.
<img width="306" alt="截屏2020-06-16 10 35 50" src="https://user-images.githubusercontent.com/28602853/84725445-3587e680-afbd-11ea-99a2-c198383f925b.png">
this is my code. i think it may be the vue's problem.
it works on html.

**Comment by andrewharvey** [comment] 2020-06-16 02:42
Sorry you'll need to post more details on what the issue is,

The following works for me:

```js
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-79.4512, 43.6568],
        zoom: 13
    });

    map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl,
            marker: {
              color: 'orange'
            }
        })
    );
```

I use this control with Vue all the time without issue.

**Comment by nooblzh** [comment] 2020-06-16 02:49
OK! I will send my project to you

**Comment by andrewharvey** [comment] 2020-06-16 02:52
> OK! I will send my project to you

Oh no please don't do that, it's likely someone will only be able to help if you have a [minimally reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by nooblzh** [comment] 2020-06-16 02:59
`<script>
import mapboxgl from 'mapbox-gl'
import MapboxGeocoder from 'mapbox-gl-geocoder'
export default {
  mounted() {
    this.init();
  },
  methods: {
    init() {
    mapboxgl.accessToken = 'pk.eyJ1Ijoid3VzdGxhdyIsImEiOiJjazlmMmlheXYwNmFnM21uemR4ZXkxMmw0In0.bAoZNRS4gdVAm90h8Kcg_g';
    var place = {
      'type': 'FeatureCollection',
      'feature': [{
        'type': 'Feature',
        'properties': {
          'icon': 'theatre'
        },
        'geometry': {
          'type': 'Point',
          'coordinates': [117.39125774810373,39.90742559489392]
        }
      }]
    };
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/light-v9',
      center: [116.39125774810373,39.90742559489392],
      zoom: 10,
      logoPosition: 'bottom-left'
    });
    var marker = new mapboxgl.Marker().setLngLat([116.39125774810373,39.90742559489392]).addTo(map);
    var geocoder = new MapboxGeocoder({
    accessToken: mapboxgl.accessToken,
    mapboxgl: mapboxgl,
    marker: {
      color: 'orange'
    }
    });
    map.addControl(geocoder);
    map.addControl(new mapboxgl.NavigationControl());
    map.addControl(new mapboxgl.GeolocateControl({
    positionOptions: {
        enableHighAccuracy: true
    },
    trackUserLocation: true,
    showUserLocation: true,
    }));
    map.addControl(new mapboxgl.ScaleControl({
      unit: 'imperial'
    }));
    map.on('load', function(){
      map.addSource('route', {
        'type': 'geojson',
        'data': {
          'type': 'Feature',
          'properties': {},
          'geometry': {
            'type': 'LineString',
            'coordinates': [
              [116.39125774810373,39.90742559489392],
              [116.59125774810373,40.90742559489392],
              [117.39125774810373,39.90742559489392]
            ]
          }
        }
      });
      map.addLayer({
        'id': 'route',
        'type': 'line',
        'source': 'route',
        'layout': {
          'line-join': 'round',
          'line-cap': 'round'
        },
        'paint': {
          'line-color': '#888',
          'line-width': 8
        }
      });
    });
  },
  }
}
</script>`

**Comment by andrewharvey** [comment] 2020-06-17 06:38
Hi @nooblzh I put together a JSFiddle from your code example and it's also using Vue and is working as expected, upon searching it will add a marker at the location you searched for along with passing the marker colour.

https://jsfiddle.net/andrewharvey4/pfy973hu/6/

So I'll close this, but feel free to post back if you can post a minimally reproducible issue.

**Closed by andrewharvey** 2020-06-17 06:38 UTC
Labels: needs information
