### ISSUE TITLE
result not selected on subsequent localGeocoder searches

### ISSUE THREAD

**Issue by yuikonnu** [mapbox/mapbox-gl-geocoder#309] opened 2019-10-22 14:35 UTC
When displaying local results and clicking on one to fly to it, you aren't able to zoom again when making a subsequent search. However, this seems to only occur if you make that search by highlighting the text then typing over it. Clearing the text manually by button or backspacing seems to let you fly to more results. Is this intended behavior?

**Comment by andrewharvey** [comment] 2019-10-23 01:05
Can you test this with the latest version 4.5.0? This was fixed in 4.5.0, although I am noticing another issue will report soon.

**Comment by yuikonnu** [comment] 2019-10-23 14:54
I've tested it using 4.5.0. It seems to now only work on every other search. Bug is consistently reproduceable. [https://webm.red/Eb6U](Here's) a link to a video demonstrating it.

**Comment by andrewharvey** [comment] 2019-10-24 01:36
Right so that's the "I am noticing another issue will report soon", which I reported at #310, I'll fold that into here...

From #310:

Using https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/ with mapbox-gl-geocoder 4.5.0, after selecting one localGeocoder result. Subsequent search and selection of a second one doesn't actually select the value.

![67347991-5ebbb880-f58f-11e9-9a10-9f597065e9de](https://user-images.githubusercontent.com/117278/67446034-d86ca880-f65a-11e9-9e80-7e46a6e29418.gif)

**Comment by andrewharvey** [comment] 2019-10-24 01:50
cc @scottsfarley93 it looks like this is a recent regression...?

**Comment by scottsfarley93** [comment] 2019-10-30 17:13
Hmmm.... This does seem to be a regression in localGeocoder behavior. 

I can take a deeper look and try for a fix later in the week.

**Comment by adamgrossman** [comment] 2019-11-06 19:41
I'm seeing this same issue, but I'm not specifying a localGeocoder. Here are my options:
```
const geocoder = new MapboxGeocoder({
  accessToken: mapbox.accessToken,
  marker: false,
  countries: 'us',
  types: 'address',
  clearAndBlurOnEsc: true,
});
```

Steps to reproduce:
1. Start with empty field
1. Make a selection
1. Select all in the input and type another address
1. Make selection
![2019-11-06 11 30 16](https://user-images.githubusercontent.com/8585262/68330950-f5f13780-0088-11ea-9109-1a952b42d439.gif)


@scottsfarley93 Any progress here?

**Comment by scottsfarley93** [comment] 2019-11-21 18:55
I've replicated the behavior you're showing above @adamgrossman. As @yuikonnu points out, I see the incorrect behavior on every other search. I looks like this is affecting both local geocoder results and regular API results. 

I believe this regression was introduced in https://github.com/mapbox/mapbox-gl-geocoder/pull/298.

**Comment by scottsfarley93** [comment] 2019-11-21 19:40
In particular, I think this line is the culprit -- https://github.com/mapbox/mapbox-gl-geocoder/pull/298/files#diff-6d186b954a58d5bb740f73d84fe39073R251. 

I added this line to re-set the selection behavior when a user enters some text (as described here in https://github.com/mapbox/mapbox-gl-geocoder/pull/298#issuecomment-538483191). I'm not sure why it's only happening on every other search. Removing this line brings back the expected behavior.

**Comment by louisdvs** [comment] 2019-12-03 07:09
Awesome that this has been resolved,  thanks @scottsfarley93 how soon can we expect this to be deployed?

**Closed** 2019-12-12 13:09 UTC
Labels: bug
