### ISSUE TITLE
IE11: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by jonaseberle** [mapbox/mapbox-gl-geocoder#194] opened 2019-03-07 11:30 UTC
When including the geocoder, e.g. on https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ ,
IE11 says Object doesn't support property or method 'includes'

I will investigate further to see how this could be circumvented. Happy for any idea.

**Comment by andrewharvey** [comment] 2019-03-07 12:05
Good catch! It looks like it's coming from https://github.com/mapbox/mapbox-gl-geocoder/blob/17f2818fb7e8f9efa955291c39e10724e6a128c0/lib/events.js#L210

For the time being you can try v3.1.1 which should work.

@scottsfarley93 did you want to address this?

**Comment by jonaseberle** [comment] 2019-03-07 12:58
Thank you @andrewharvey - that circumvents that problem but v3.1.1 uses Promises which IE11 does not have.
3.1.1 with this polyfill https://www.npmjs.com/package/promise-polyfill works.

**Comment by andrewharvey** [comment] 2019-03-07 13:11
True, versions later than v2.3.0 need a promise-polyfill for older browsers. This stems from https://github.com/mapbox/mapbox-sdk-js#installation. We should do a better job of documenting this in the README, similar to https://github.com/mapbox/mapbox-sdk-js#installation.

**Comment by scottsfarley93** [comment] 2019-03-07 19:39
I can fix this in the minor refactor I'm doing in #189. 

I wonder if we can add some tests that capture regressions on IE11 going forward.

**Comment by scottsfarley93** [comment] 2019-03-14 20:34
This should now be resolved in v3.1.6.

**Closed by scottsfarley93** 2019-03-14 20:34 UTC
Labels: bug
