### ISSUE TITLE
MapboxGeocoder Limit search to country not working

### ISSUE THREAD

**Issue by Antoine-lb** [mapbox/mapbox-gl-geocoder#381] opened 2020-07-07 09:38 UTC
**Versions:**
"mapbox-gl": "^1.11.0",
"mapbox-gl-geocoder": "^2.0.1",

**browser**: Firefox, Chromium and Safari same result

### Steps to Trigger Behavior

 1. Add `countries` limit in the MapboxGeocoder initialization
 2. Results from all the world still showing anyways

There is nothing in the logs

### Link to Demonstration
The example in the documentation is not working either:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-limit-region/

But https://docs.mapbox.com/help/tutorials/local-search-geocoding-api/ does work, but it uses `bbox` to delimit, not `countries`.

**Comment by andrewharvey** [comment] 2020-07-07 11:40
Works for me in the example https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-limit-region/ even with only the `countries` option without `bbox`. Could you post a minimal reproducible example?

**Comment by Antoine-lb** [comment] 2020-07-07 12:21
I think we are taking about multiple things, sorry for being a bit of a mess.

## For the documentation:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-limit-region/ works on Chromium but not on Firefox (I deactivated all my privacy plugins and opened a private browser but nothing). 
On firefox it does not show anything no matter what I type, the result is always 'No result found' (my query is `sydn` for Sydney which is in the delimited area). Chromium finds it pretty well.

## In my code:
I'm importing `mapbox-gl` and `mapbox-gl-geocoder` with yarn and initializing `mapbox-gl-geocoder` to be a field **outside** of the map, is working well (e.g. I type a location, and the map points to that area properly). But when I add `countries: "au",` in the `MapboxGeocoder` config it is completely ignored (meaning that it still shows me results from all the world). This is independend of the browser (same result in Firefox and Chromium).

My problem is that there is nothing logged in the console. And actually I don't know if is even reading the argument because if I put dummy data (e.g. `toto: "asdf",`) in the config, but nothing appears in the log, and `marker: { color: "orange", },` is not working either.

Hope you can give me some hints on where to look, thanks!

**Comment by andrewharvey** [comment] 2020-07-07 12:39
I also tested on Firefox and it's working for me, do you see any errors in the developer console?

Looks like you're doing something wrong in your code then, unless you can post a minimal reproducible example of your code, sorry there's not much we can do.

**Comment by Antoine-lb** [comment] 2020-07-07 13:57
So I'm in a React/Gastby environment. I'm loading this component with `@loadable/component` because `mapbox-gl-geocoder` needs the `window` object and it was breaking the Server Side Rendering.

I just downloaded the CSS files for it to be loaded stically (Gatsby is a static site builder, so I rather have all the files locally). It works perfect for `mapbox-gl`  but for `mapbox-gl-geocoder` some stuff is broken, it did load some style but it did not take the `input` field. Can the courty limit be broken because of the styles being imported in a weird way?

I started coding this today so all the Mapbox Libs are fresh from today.

Sorry for being a little verbose with the entire code, but maybe you can spot something wrong. Thanks!

```
import React, { useEffect } from "react"
import mapboxgl from "mapbox-gl" // v ^1.11.0
import MapboxGeocoder from "mapbox-gl-geocoder" // v ^2.0.1

import styled from "styled-components"

import "./mapbox-v1-11-0.css" // downloaded the files for simplicity
import "./mapbox-geocoder-v4-5-1.css"

const MapboxWrapperContainer = styled.div`
  #geocoder-container > div {
    min-width: 50%;
    margin-left: 25%;
  }
`
const MapboxWrapperMap = styled.div`
  height: 400px;
`

const MapboxWrapper = () => {
  useEffect(() => {
    mapboxgl.accessToken =
      "pk.my.key"
    const map = new mapboxgl.Map({
      container: "mapbox-map",
      style: "mapbox://styles/antoine-lb/ckcbnzqf25cow1ipheuedw6hm",
      center: [-70.64, -33.45], // starting position [lng, lat]
      zoom: 11, // starting zoom
    })

    var marker = new mapboxgl.Marker()
      .setLngLat([-70.609994, -33.4214846])
      .addTo(map)

    var geocoder = new MapboxGeocoder({
      accessToken: mapboxgl.accessToken,
      mapboxgl: mapboxgl,
      countries: "au",
    })
    document.getElementById("geocoder").appendChild(geocoder.onAdd(map))
  })

  return (
    <MapboxWrapperContainer>
      <div id="geocoder"></div>
      <MapboxWrapperMap id="mapbox-map"></MapboxWrapperMap>
    </MapboxWrapperContainer>
  )
}

export default MapboxWrapper

```

**Comment by andrewharvey** [comment] 2020-07-07 23:20
I can't see anything wrong there so unfortunately I'm not going to be much help. If you can replicate with vanilla js without React then I can take another look.

**Comment by Antoine-lb** [comment] 2020-07-08 09:33
❌ Kind of works, but with some magic bugs (that don't show errors):
```
yarn add mapbox-gl
yarn add mapbox-gl-geocoder
...
import mapboxgl from "mapbox-gl"
import MapboxGeocoder from "mapbox-gl-geocoder"
```

✅ Works as expected, but package import does not make sence:
```
yarn add mapbox-gl
yarn add @mapbox/mapbox-gl-geocoder
...
import mapboxgl from "mapbox-gl"
import MapboxGeocoder from "@mapbox/mapbox-gl-geocoder"
```

I tried to import `@mapbox/mapbox-gl` to be more consistent, but the package does not exists, making the solucion even more confusing.

I spent 2 days on this, how can we make sure this does not happen again?
Ideas:
- explaining what is the difference between `@mapbox/mapbox-gl-geocoder` and `mapbox-gl-geocoder`
- put all JS modules under `@mapbox` to be more consistent
- print wornings when installing and using `mapbox-gl-geocoder` for users to expect it to work differently

extra suggestion:
- please build a official Mapbox plugin-in for GatsbyJS, is a very popular framework now

**Comment by andrewharvey** [comment] 2020-07-08 10:40
Ahh I should have picked up on that from your original report

> "mapbox-gl-geocoder": "^2.0.1",

That's a very old release, as you found on npm the package is now published under the `@mapbox` namespace this is documented at https://github.com/mapbox/mapbox-gl-geocoder#usage-with-a-module-bundler.

mapbox-gl is not nampspaced under `@mapbox` so the correct import is:

```js
import mapboxgl from "mapbox-gl"
import MapboxGeocoder from "@mapbox/mapbox-gl-geocoder"
```

> explaining what is the difference between @mapbox/mapbox-gl-geocoder and mapbox-gl-geocoder

I think that would just make things less clear, `mapbox-gl-geocoder` is an old version so there's no reason to use it for new projects. https://github.com/mapbox/mapbox-gl-geocoder#usage-with-a-module-bundler show's both the npm install and import steps with the `@mapbox` namespace.

but you're not the only one https://twitter.com/stevage1/status/1275659496535273473

> a page in the documentation for how to import modules

It's at https://github.com/mapbox/mapbox-gl-geocoder#usage-with-a-module-bundler and all the examples like at https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ all link back to the github repo. How do you think this could be improved?

**Comment by andrewharvey** [comment] 2020-07-08 10:41
Since the original issue here is solved (or should be if you use the latest version under the `@mapbox` namespace) I'll close this ticket, but if you have suggestions on improving the documentation please feel free to open a new ticket.

**Closed by andrewharvey** 2020-07-08 10:41 UTC
